services:
  # Django 后端服务
  - type: web
    name: django-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.8
      - key: RENDER
        value: "true"
      - key: DJANGO_SETTINGS_MODULE
        value: server.settings
      - key: DATABASE_URL
        fromDatabase:
          name: planetscale-db
          property: connectionString
    autoDeploy: true

# PlanetScale 数据库
databases:
  - name: planetscale-db
    databaseName: web_b2b
    user: web_b2b_user
    plan: free
